version: '2.0'

services:

  db:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: deloitte
      MYSQL_USER: deloitteuser
      MYSQL_PASSWORD: Password1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080